<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="26830" started-at="2022-06-23T16:46:19 IST" finished-at="2022-06-23T16:46:46 IST">
    <groups>
      <group name="Sanity">
        <method signature="AccountCreationPageTest.verifyAccountPageTest()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="verifyAccountPageTest" class="com.mystore.testcases.AccountCreationPageTest"/>
      </group> <!-- Sanity -->
    </groups>
    <test name="Test" duration-ms="26830" started-at="2022-06-23T16:46:19 IST" finished-at="2022-06-23T16:46:46 IST">
      <class name="com.mystore.testcases.AccountCreationPageTest">
        <test-method status="PASS" signature="beforeSuit()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="beforeSuit" is-config="true" duration-ms="182" started-at="2022-06-23T16:46:19 IST" finished-at="2022-06-23T16:46:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuit -->
        <test-method status="PASS" signature="loadConfig()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="loadConfig" is-config="true" duration-ms="0" started-at="2022-06-23T16:46:19 IST" finished-at="2022-06-23T16:46:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="launchBrowser" is-config="true" duration-ms="8161" started-at="2022-06-23T16:46:19 IST" finished-at="2022-06-23T16:46:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="verifyAccountPageTest()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="verifyAccountPageTest" duration-ms="18151" started-at="2022-06-23T16:46:27 IST" finished-at="2022-06-23T16:46:45 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.mystore.testcases.AccountCreationPageTest.verifyAccountPageTest(AccountCreationPageTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountPageTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="tearDown" is-config="true" duration-ms="222" started-at="2022-06-23T16:46:46 IST" finished-at="2022-06-23T16:46:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuit()[pri:0, instance:com.mystore.testcases.AccountCreationPageTest@306279ee]" name="afterSuit" is-config="true" duration-ms="515" started-at="2022-06-23T16:46:46 IST" finished-at="2022-06-23T16:46:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- com.mystore.testcases.AccountCreationPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
